### ISSUE TITLE
load_file should use a Path type for the path

### ISSUE THREAD

**Issue by wez** [mockersf/hocon.rs#10]
Something like this preserves the ergonomics of passing in a string while also working with file names that are not representable as UTF-8, which is possible on the majority of posix systems, as well as on windows systems:

```rust
pub fn load_file<P: AsRef<Path>>(&self, path: P) -> Result<Self, Error> {
        let mut file_path = path.as_ref().to_path_buf();
```

**Comment by mockersf** [comment]
thanks, this should work in the next release!

**Comment by wez** [comment]
Thanks; confirmed that I can pass a Path through now!
