### ISSUE TITLE
Overly permissive?

### ISSUE THREAD

**Issue by wez** [mockersf/hocon.rs#15]
Here's a little example:

```
#[derive(Deserialize, Default)]
struct Foo {
  #[serde(default)]
  foo: bool,
}
```

with this invalid input file:

```
foo: "
```

when loaded with:

```
  let file = match hocon::HoconLoader::new().strict().load_file(p) {
      Err(err) => bail!("Error opening {}: {}", p.display(), err),
      Ok(file) => file,
  };
  let cfg: Self = file
       .resolve()
       .map_err(|e| format_err!("Error parsing HOCON from {}: {}", p.display(), e))?;
```

The `cfg` ends up with the default values for the fields rather than reporting any errors.

Is this expected behavior?

**Comment by mockersf** [comment]
it works as expected (but error message can be improved) with
```
foo: ""
```
as quoted string in Hocon should be with double quote ([quoted strings unchanged from JSON](https://github.com/lightbend/config/blob/master/HOCON.md#unchanged-from-json))

it should fail at the parsing level when using single quote, but right now it's not an error to have unparsed parts of the file at the end...

**Comment by mockersf** [comment]
it will now fail in strict mode to have remaining parts of the file unparsed
