### ISSUE TITLE
"file could not be parsed completely" with trailing CRLF newline

### ISSUE THREAD

**Issue by ennis** [mockersf/hocon.rs#24]
The following snippet tries to load the document `{a:7}` with a trailing CRLF newline (windows-style line endings), but panics with: `failed to load: Deserialization { message: "file could not be parsed completely" }`

```rust
use hocon::HoconLoader;

fn main() {
    let mut loader = HoconLoader::new().strict();
    let src = "{ a: 7 }\r\n";
    loader.load_str(src).expect("failed to load");
}
```
At a glance, it seems that the nom parser uses [`nom::newline`](https://docs.rs/nom/4.0.0/nom/fn.newline.html), which only recognizes `\n`. Maybe [`nom::line_ending`](https://docs.rs/nom/4.0.0/nom/fn.line_ending.html) would fix that as a drop-in replacement?

Also, I'm not sure that this is a bug: maybe the HOCON spec simply does not allow non-LF line endings? The spec did not seem entirely clear to me on that point.

**Comment by mockersf** [comment]
Thank you for reporting this.
From HOCON spec, I would say only `\n` is authorised but I don't think that's practical. plus for consistency sake, as the parser currently accept `\r` everywhere...
