### ISSUE TITLE
Support for 'dashed' property names

### ISSUE THREAD

**Issue by everson** [mockersf/hocon.rs#34]
Hi, thanks for this project. 

I am trying to migrate a project from Scala to Rust and keep the config for backwards compatibility with the automation. I was hoping to be able read our config, which uses dashes to separate words, instead of underlines. Is there a way to accomplish this? I didn't see any configuration knobs.

Example config:
```
  concurrency: {
    server-threads: 16
    client-threads: 8
    foo-bar: {
       nested-config: true
    }
  }
```

**Comment by mockersf** [comment]
Hello, thank you for trying it out!

I tried with your conf snippet, it si loading for me, you can see [here](https://github.com/mockersf/hocon.rs/blob/acbe4f935613d3df9c2a63b045756c573426eaa3/tests/parse.rs#L909)

What is the issue you're facing?

**Comment by everson** [comment]
Oh, Sorry, only after opening this it occurred to me that this setting might be in serde instead:

I was looking at this exact moment to create a minimal snippet for you. 

https://serde.rs/attr-rename.html

e.g.
```
#[derive(Serialize)]
#[serde(rename_all = "kebab-case")]
struct Person {
    first_name: String,
    last_name: String,
}
```
that works.

**Comment by everson** [comment]
Thank you a lot. Sorry for the false alarm.
