### ISSUE TITLE
load_file doesnt fail with non-existent file

### ISSUE THREAD

**Issue by lostiniceland** [mockersf/hocon.rs#47]
I can pass a &Path with total bogus to HoconLoader::load_file and not get a IOError. Instead, an empty Hocon struct is returned as it seems

Of course I can check this on my application but I wonder if this was intentional in order to merge multiple dynamic hocon files or just a bug.

**Comment by mockersf** [comment]
Thank you for your report!

I just added a test, and it's a success: https://github.com/mockersf/hocon.rs/commit/925c00d6cdb7eea145231c1763361c9300f2cf4c

https://github.com/mockersf/hocon.rs/blob/925c00d6cdb7eea145231c1763361c9300f2cf4c/tests/load.rs#L21-L26

Could you share your code?

**Comment by lostiniceland** [comment]
Weird. Maybe I am doing something wrong.

https://github.com/lostiniceland/inquest/blob/main/src/input/mod.rs#L12-L20
I am creating a Path in my CLI part and pass it along to this function.

I did some local debugging just now and I can confirm that I am getting a Hocon struct, but when doing something with it the result, of course, is a None

**Comment by mockersf** [comment]
Couldn't find anything in your code that would explain that...

**Comment by lostiniceland** [comment]
I am closing this for now and investigate further. Thanks for adding the test to make sure.
